version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: careerops-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: careerops
      POSTGRES_USER: careerops
      POSTGRES_PASSWORD: careerops_password
    ports:
      - "5433:5432"
    volumes:
      - careerops_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U careerops -d careerops"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: careerops-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - careerops_redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: careerops-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - careerops_miniodata:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 20


  minio-init:
    image: minio/mc:RELEASE.2024-11-21T17-21-54Z
    container_name: careerops-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin123 &&
      mc mb -p local/careerops || true &&
      mc anonymous set none local/careerops || true &&
      echo 'MinIO bucket careerops is ready.' "
    restart: "no"

  metabase:
    image: metabase/metabase:v0.50.21
    container_name: careerops-metabase
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: careerops
      MB_DB_PORT: 5432
      MB_DB_USER: careerops
      MB_DB_PASS: careerops_password
      MB_DB_HOST: postgres

  adminer:
    image: adminer:4
    container_name: careerops-adminer
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  careerops_pgdata:
  careerops_redisdata:
  careerops_miniodata:
